on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          # Replace the build command below with your actual build command
          echo "Building the project..."
          # Your build command goes here

      - name: Print message
        run: echo "Build completed successfully!"

      - name: Checkout private repo remotely
        uses: actions/checkout@v2
        with:
          repository: ICT-CET-Activities/hiddenRepo
          # Optionally, you can specify the branch or tag name for the private repository
          ref: main
          # Optionally, you can specify the destination directory for the checkout
          path: folder_yx
          # Replace "MY_TOKEN" with the name of your secret that contains the access token for the private repo
          token: ${{ secrets.MY_TOKEN }}

      - name: Show hidden files
        run: |
          cd folder_yx
          ls
