on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.URL }}
          ref: main
          token: ${{ secrets.MY_TOKEN }}
          path: /   # Optionally, you can specify the destination directory for the checkout

      - name: Show hidden files
        run: |
         # cd /
          ls -a
